// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.11.2
// source: eventual.proto

package eventualrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AppendEntriesInEventualRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MapLattice []byte `protobuf:"bytes,1,opt,name=map_lattice,json=mapLattice,proto3" json:"map_lattice,omitempty"`
	Version    int32  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"` // version of the log.value
}

func (x *AppendEntriesInEventualRequest) Reset() {
	*x = AppendEntriesInEventualRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eventual_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppendEntriesInEventualRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntriesInEventualRequest) ProtoMessage() {}

func (x *AppendEntriesInEventualRequest) ProtoReflect() protoreflect.Message {
	mi := &file_eventual_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntriesInEventualRequest.ProtoReflect.Descriptor instead.
func (*AppendEntriesInEventualRequest) Descriptor() ([]byte, []int) {
	return file_eventual_proto_rawDescGZIP(), []int{0}
}

func (x *AppendEntriesInEventualRequest) GetMapLattice() []byte {
	if x != nil {
		return x.MapLattice
	}
	return nil
}

func (x *AppendEntriesInEventualRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type AppendEntriesInEventualResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *AppendEntriesInEventualResponse) Reset() {
	*x = AppendEntriesInEventualResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_eventual_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppendEntriesInEventualResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntriesInEventualResponse) ProtoMessage() {}

func (x *AppendEntriesInEventualResponse) ProtoReflect() protoreflect.Message {
	mi := &file_eventual_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntriesInEventualResponse.ProtoReflect.Descriptor instead.
func (*AppendEntriesInEventualResponse) Descriptor() ([]byte, []int) {
	return file_eventual_proto_rawDescGZIP(), []int{1}
}

func (x *AppendEntriesInEventualResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_eventual_proto protoreflect.FileDescriptor

var file_eventual_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x75, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x5b, 0x0a, 0x1e, 0x41, 0x70, 0x70, 0x65, 0x6e, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65,
	0x73, 0x49, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x75, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x61, 0x70, 0x5f, 0x6c, 0x61, 0x74, 0x74, 0x69, 0x63,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x6d, 0x61, 0x70, 0x4c, 0x61, 0x74, 0x74,
	0x69, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x3b, 0x0a,
	0x1f, 0x41, 0x70, 0x70, 0x65, 0x6e, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x49, 0x6e,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x75, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x32, 0x6a, 0x0a, 0x08, 0x45, 0x56,
	0x45, 0x4e, 0x54, 0x55, 0x41, 0x4c, 0x12, 0x5e, 0x0a, 0x17, 0x41, 0x70, 0x70, 0x65, 0x6e, 0x64,
	0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x49, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x75, 0x61,
	0x6c, 0x12, 0x1f, 0x2e, 0x41, 0x70, 0x70, 0x65, 0x6e, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65,
	0x73, 0x49, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x75, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x20, 0x2e, 0x41, 0x70, 0x70, 0x65, 0x6e, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x69,
	0x65, 0x73, 0x49, 0x6e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x75, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x10, 0x5a, 0x0e, 0x2e, 0x2f, 0x3b, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x75, 0x61, 0x6c, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_eventual_proto_rawDescOnce sync.Once
	file_eventual_proto_rawDescData = file_eventual_proto_rawDesc
)

func file_eventual_proto_rawDescGZIP() []byte {
	file_eventual_proto_rawDescOnce.Do(func() {
		file_eventual_proto_rawDescData = protoimpl.X.CompressGZIP(file_eventual_proto_rawDescData)
	})
	return file_eventual_proto_rawDescData
}

var file_eventual_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_eventual_proto_goTypes = []interface{}{
	(*AppendEntriesInEventualRequest)(nil),  // 0: AppendEntriesInEventualRequest
	(*AppendEntriesInEventualResponse)(nil), // 1: AppendEntriesInEventualResponse
}
var file_eventual_proto_depIdxs = []int32{
	0, // 0: EVENTUAL.AppendEntriesInEventual:input_type -> AppendEntriesInEventualRequest
	1, // 1: EVENTUAL.AppendEntriesInEventual:output_type -> AppendEntriesInEventualResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_eventual_proto_init() }
func file_eventual_proto_init() {
	if File_eventual_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_eventual_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppendEntriesInEventualRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_eventual_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppendEntriesInEventualResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_eventual_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_eventual_proto_goTypes,
		DependencyIndexes: file_eventual_proto_depIdxs,
		MessageInfos:      file_eventual_proto_msgTypes,
	}.Build()
	File_eventual_proto = out.File
	file_eventual_proto_rawDesc = nil
	file_eventual_proto_goTypes = nil
	file_eventual_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// EVENTUALClient is the client API for EVENTUAL service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EVENTUALClient interface {
	AppendEntriesInEventual(ctx context.Context, in *AppendEntriesInEventualRequest, opts ...grpc.CallOption) (*AppendEntriesInEventualResponse, error)
}

type eVENTUALClient struct {
	cc grpc.ClientConnInterface
}

func NewEVENTUALClient(cc grpc.ClientConnInterface) EVENTUALClient {
	return &eVENTUALClient{cc}
}

func (c *eVENTUALClient) AppendEntriesInEventual(ctx context.Context, in *AppendEntriesInEventualRequest, opts ...grpc.CallOption) (*AppendEntriesInEventualResponse, error) {
	out := new(AppendEntriesInEventualResponse)
	err := c.cc.Invoke(ctx, "/EVENTUAL/AppendEntriesInEventual", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EVENTUALServer is the server API for EVENTUAL service.
type EVENTUALServer interface {
	AppendEntriesInEventual(context.Context, *AppendEntriesInEventualRequest) (*AppendEntriesInEventualResponse, error)
}

// UnimplementedEVENTUALServer can be embedded to have forward compatible implementations.
type UnimplementedEVENTUALServer struct {
}

func (*UnimplementedEVENTUALServer) AppendEntriesInEventual(context.Context, *AppendEntriesInEventualRequest) (*AppendEntriesInEventualResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppendEntriesInEventual not implemented")
}

func RegisterEVENTUALServer(s *grpc.Server, srv EVENTUALServer) {
	s.RegisterService(&_EVENTUAL_serviceDesc, srv)
}

func _EVENTUAL_AppendEntriesInEventual_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendEntriesInEventualRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EVENTUALServer).AppendEntriesInEventual(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/EVENTUAL/AppendEntriesInEventual",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EVENTUALServer).AppendEntriesInEventual(ctx, req.(*AppendEntriesInEventualRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _EVENTUAL_serviceDesc = grpc.ServiceDesc{
	ServiceName: "EVENTUAL",
	HandlerType: (*EVENTUALServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AppendEntriesInEventual",
			Handler:    _EVENTUAL_AppendEntriesInEventual_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "eventual.proto",
}
